# Generated by Django 6.0.3 on 2026-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_estudiante_ano_cursado_estudiante_carnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(blank=True, choices=[('LAF', 'Licenciatura Administrativa con Énfasis en Finanzas'), ('LCM', 'Licenciatura Comercial con Énfasis en Mercadeo'), ('IGI', 'Ingeniería en Gestión Industrial'), ('ICE', 'Ingeniería Cibernética Electrónica'), ('IME', 'Ingeniería Mecánica y Energías Renovables'), ('IMS', 'Ingeniería Mecatrónica y Sistemas de Control'), ('IEM', 'Ingeniería Electromédica')], max_length=5, null=True),
        ),
    ]
