# Generated by Django 6.0.3 on 2026-03-21 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_estudiante_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='equipo',
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.equipo')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='usuarios.prestamo')),
            ],
        ),
    ]
